### ISSUE TITLE
Bylaws?

### ISSUE THREAD

**Issue by anantshri** [OWASP/www-policy#10]
OWASP used to have bylaws as those are not transfered over to this portal and doesn't appear on the new website is it safe to assume OWASP doesn't have bylaws now or were they not considered worthy enough to be transfered over during initial migration and 6 months after 
https://wiki.owasp.org/index.php/OWASP_Foundation_ByLaws

If i have to speculate i would say this was not transferred as this page didn't had a lot of traffic and was considered disfunctional.

**Comment by mikemccamon** [comment]
Bylaws are linked to the GOVERNANCE submenu. https://owasp.org/assets/legal/bylaws
