### ISSUE TITLE
Update logos on www-policy/operational/branding to reflect trademark registration

### ISSUE THREAD

**Issue by davewichers** [OWASP/www-policy#18]
All the logos on this page say TM, but should now use the Circle R I believe, as OWASP is now a registered trademark. I don't know if there are other logs on the OWASP site that need updating too, but I happened to notice these.

**Comment by kingthorin** [comment]
This appears to have been done:
![image](https://user-images.githubusercontent.com/7570458/100919931-76f74a00-34a8-11eb-93d8-929ed327b8ff.png)
