### ISSUE TITLE
Remove hostile items/language from leaders policy

### ISSUE THREAD

**Issue by stevespringett** [OWASP/www-policy#20]
The proposed leaders policy has items which are hostile to tool projects, includes governance items that OWASP has never proven capable of, and items that are not technically possible due to infrastructure limitation.

Ideally, the leaders policy should be DELETED along with all history since there are no objectives, goals, conversations, etc, about why the policy exists in its current form.

Short of deleting it, I will be submitting a PR that removes large portions of it.

**Comment by vanderaj** [comment]
Steve, per the PR being closed, I'm closing this one too. Let's work together on a revised leaders policy that documents the lifecycle and responsibilities of leaders.
