### ISSUE TITLE
Create project exit policy

### ISSUE THREAD

**Issue by stevespringett** [OWASP/www-policy#22]
OWASP has relaxed policies with regard to copyright of code projects as the foundation does not require transfer of copyright. Other software foundations have this requirement. OWASP does not. This leaves the possibility of leaders of code projects to exit the foundation with their projects without having to fork them.

A policy needs to be created that would:
* provide a frictionless transfer from an OWASP project to an independent project
* maintain historical project information including:
  * project level at the time of exit
  * project leader(s) at the time of exit
  * project description at the time of exit
* provide an indication that the project is archived
* inform the user that the project has 'graduated' and is no longer an OWASP project
* provide a single link to where the independent project can be found
* require the independent project to discontinue use of OWASP in their branding

The policy should address the name of the project as well. 

* Does the name of the independent project need to change?

**Comment by kingthorin** [comment]
>The policy should address the name of the project as well.
>
>   * Does the name of the independent project need to change?

For my two cents names belong to projects not to OWASP. If ZAP were to cease being an OWASP project for whatever reason it would still be ZAP. If some other team/group within OWASP wanted to fork it that initiative would need a new name.

Though that is only my two cents, other might have a different take on it.

**Comment by vanderaj** [comment]
We need to create a proper Project policy, and kill with fire the Project Spending policy, which simply puts roadblocks in the way of project leaders, similar to what passed today for the Chapter policy. I'd appreciate your assistance in working on a proper Project policy, understanding that if OWASP incubates or funds grants and so on, that OWASP has a direct IP interest in that project. The project exit policy should of a fork nature, similar to LibreOffice and MariaDB. When the key contributors leave, they take the brains behind a project with them, but our community expects OWASP projects like the OWASP Top 10 or SAMM to be around for all time, even if a key project leader or entire team leaves. We can't just have a situation where the project can leave completely and destroy years of work and history. Let's talk about this at the next project committee meeting, as I feel it's important to get on the same page and be open source aligned.

**Comment by hblankenship** [comment]
Closing comment per policy review process - when the policy is in a review period please provide comments to the policy review team.
