### ISSUE TITLE
Align membership policy and bylaws

### ISSUE THREAD

**Issue by vanderaj** [OWASP/www-policy#24]
Needs to address lifetime, honorary, and complementary changes per the vote on October 20:

2020-10-20
Resolved, the Board directs the Foundation to provide automated complimentary Membership to the top 5 active leaders of chapters, projects, events, and committees, effective November 1st, 2020, and monthly after that. Honorary Membership will become an award made by the Board, and changed to be for five years in recognition of extraordinary service to the OWASP Community. Regional pricing will be made available to all classes of paid Membership. 

This must be reflected in the membership policy also, preferably by adopting the same language as from the bylaws.

**Comment by rewtd** [comment]
Thank you @vanderaj
