### ISSUE TITLE
Expense Reimbursement Policy

### ISSUE THREAD

**Issue by jcfergus** [OWASP/www-policy#3]
With respect to the proposed expense-reimbursement policy (since it's not in the form of a PR I can't comment on it directly) - it seems to be entirely reasonable to me.  The two comments I have are: 

1.  There are two sections regarding Travel - while not necessarily in conflict with each other; it's slightly confusing as to what the difference is.   Also, does the "exec director approval" requirement for speaker travel supercede the $2500 guidance?  (i.e. if we want to have a speaker travel to speak to our chapter but can do it for well less than $2500, is exec director approval still required)?  

2.  While this covers individual expenses, some form of guidance with respect to cumulative expenses throughout the year might be nice as well, if that is a concern.

**Comment by RG-OWASP** [comment]
I have created a Chapter Tier chart that attempts to formalize the classifications of, criteria, and entitlements of chapters at OWASP. Please comment. This will helping our Fair and Reasonable Expenses discussion as well.
[Chapter Tiers.docx](https://github.com/OWASP/www-policy/files/4137439/Chapter.Tiers.docx)

**Comment by act1vand0** [comment]
I agree with @RG-OWASP that we need some kind of classification for chapters, e.g. one that is brand new and will (hopefully) hold 4-5 events a year vs. one that's been around for a while, holds 8-12 events a year, and is a key player in bringing money into the Foundation by having a successful local conference with major revenue, bringing in corporate sponsors, etc.

I also agree with @mikemccamon that for the smaller chapters with low activity, it'd be helpful to have a centralized budget for all of them. I tend to think this would be the case for most chapters.  This way they can continue to run a good (but small and/or low activity) chapter while we're able to alleviate the Foundation from managing separate budgets for all of them.

I'm looking forward to the conversation where we can discuss and formalize the idea of chapter tiers, and how we'd adjust the [expense-reimbursement](https://github.com/OWASP/www-policy/blob/4eaefcddfdf7ec951477c9a595f4996d67112c1d/operational/expense-reimbursement.md) doc to reflect this.

**Comment by bkimminich** [comment]
The chapter classification criteria proposed are very vague. Also it seems the entire discussion boils down to "does local conferences = brings more money = allowed to spend more money" which could be solved by making bigger expenses part of said conference budget plans.

Just as an example: Expecting to get an annual chapter christmas party sponsored has a much different vibe than budgeting a conference after-party for the organizers of a conference.

**Comment by vanderaj** [comment]
Hi everyone, the expenses system will be shortly reformed, so please work with us in the various policy channels on Slack.
