### ISSUE TITLE
Branding - missing mentioned assets and collatoral

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-policy#6]
https://owasp.org/www-policy/operational/branding

~~Has at least one broken link: `[Deja Vu](http://www.fontsquirrel.com/fonts/DejaVu-Serif` and~~ none of the logos or templates are linked to actual usable assets.

**Comment by bkimminich** [comment]
Logos can be found here in all kinds of formats: https://github.com/OWASP/owasp-swag/tree/master/owasp/logos

**Comment by kingthorin** [comment]
Closing This has been addressed by PRs and the work of the Policy Review Team.
