### ISSUE TITLE
No Shared Services for Branches Clarification

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#69]
From: Lisa Jones @latf6711 

`Regional Chapter will pool OWASP Foundation shared services for their branches. Shared services are not provided directly to the Branches.`

What does this mean?

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.
