### ISSUE TITLE
Branch Shared Services Clarification

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#78]
From: Lisa Jones @latf6711 

`If an AppSec Day event results in a net profit, the Regional Chapter may elect to provide an OWASP meeting platform group or other shared services (under the regular OWASP account) for an active Branch at the Regional Chapter’s own expense, if approved by the leaders of the Regional Chapter. Shared services will be provided by the OWASP Foundation, on the condition that the profits from the Regional Conference can cover the costs of the service. The OWASP Foundation shall not bear the costs of Branches.`

How is this to be tracked? If there are only enough funds to pay for a year then what happens?

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.
