### ISSUE TITLE
Branch Shared Services Revision

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#81]
From: Dirk Wetter @drwetter 

**Current:** `Regional Chapter will pool OWASP Foundation shared services for their branches. Shared services are not provided directly to the Branches.`

**Suggested:** `A regional chapter decides whether to create and terminate associated regional branches. Termination of shared services for regional branches must be aligned with the respective regional chapter.`

The reasoning is to establish a mandatory communication channel from the Foundation to local Chapters which are managing the regional branches. This serves to preserve the local community in case it can be revived by the Chapter.

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.

**Comment by drwetter** [comment]
WTH!

Before closing this how about responding to my mails before, how about a little bit of communication, huh?
Either from the board of from the ED -- when pedaling back. Keep in mind that our chapter spend hard work into this, like 30 man hours.

The lack of communication in this matter is really aggravating, to put it politely.
