### ISSUE TITLE
Branch Shared Services Budget Sources

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#82]
From: Dirk Wetter @drwetter 

**Current:** `If an AppSec Day event results in a net profit, the Regional Chapter may elect to provide a OWASP meeting platform group or other shared service (under the regular OWASP account) for an active Branch  at the Regional Chapter’s own expense, if approved by the leaders of the Regional Chapter. Shared services will be provided by the OWASP Foundation, on condition that the profits from the Regional Conference can cover the costs of the service. The OWASP Foundation shall not bear the costs of Branches.`

**Suggested:** `A Regional Chapter may elect on behalf of the Regional Branch to the OWASP Foundation to provide a OWASP meeting platform group or other shared service (under the regular OWASP account) at the Regional Chapter’s own expense, if approved by the leaders of the Regional Chapter. Shared services will be provided by the OWASP Foundation. The Regional Chapter may be asked to contribute to the costs of the service for its branches, for example via AppSec Day net profit, restricted gifts, attributed membership fees or attributed donations.`

The reasoning of this change is to emphasize that the decision to grant access to shared infrastructure is made by the regional chapter and to extend the list of possible budget sources besides an AppSec Day event. Local meetings are the core idea of building a community and to foster networking amongst the community, share knowledge and participate in other OWASP activities. A pooled regional Chapter meetup account seems to be unsuitable to organize local meetings over a large area like Germany.

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.
