### ISSUE TITLE
Branch Naming Schema

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#84]
From: Dirk Wetter @drwetter 

**Current:** `Branches should follow the naming rules of City chapters.`

**Suggested:** `Regional branches should follow the naming rules of City chapters. They may choose to include the name of the region.`

The Regional Chapter Branch might cover more than just one city, so the possibility to cover an area in the branch name would be beneficial. An example would be our current “Ruhrpott” Stammtisch / Regional Chapter Branch, which covers cities such as Essen, Düsseldorf, and Dortmund. The cities are very close together, so having different Regional Chapter Branches for them wouldn’t be desired. Ruhrpott (or Ruhrgebiet) is the common name of the region unifying those cities. (A US example would be the Bay Area Chapter.)

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.
