### ISSUE TITLE
Remove Branch Leader Benefits

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#85]
From: Dirk Wetter @drwetter 

**Current:** `Leader benefits will only apply to the first five branch leaders.`

**Suggested:** Remove the statement completely.

We guess that this is a copy/paste error and that regional branch leaders aren’t supposed to receive leader benefits (unless they’re also leaders of the Regional Chapter or a Project). Hence the sentence should be removed.

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.
