### ISSUE TITLE
Why special treatment for Appsec California

### ISSUE THREAD

**Issue by anantshri** [OWASP/www-policy#9]
In events policy as listed here https://github.com/OWASP/www-policy/blob/master/operational/events.md reference screenshot attached

<img width="1002" alt="appsec_cali" src="https://user-images.githubusercontent.com/236843/82933355-64ef9880-9fa7-11ea-8826-702a178f291b.png">

Why is there a special treatment for Appsec California and not any other chapter if there are specific conditions what if another event makes that cut. why specifically call out one chapter and make them unique. I would advice to generalize the conditions if any and remove any specific chapter references.

**Comment by vanderaj** [comment]
This is no longer a part of the Events policy.
